stations:
   - id: 1
     name: "Minsk"
     type: "Cargo and Passenger"
   - id: 2
     name: "Moscow"
     type: "Passenger"
   - id: 3
     name: "Saint-Petersburg"
     type: "Cargo and Passenger"
   - id: 4
     name: "Gomel"
     type: "Cargo"
   - id: 5
     name: "Brest"
     type: "Passenger"
   - id: 6
     name: "Warsaw"
     type: "Cargo and Passenger"
   - id: 7
     name: "Vitebsk"
     type: "Cargo"
   - id: 8
     name: "Grodno"
     type: "Cargo and Passenger"
   - id: 9
     name: "Vilnius"
     type: "Cargo and Passenger"
   - id: 10
     name: "Riga"
     type: "Passenger"
   - id: 11
     name: "Gdansk"
     type: "Cargo"
   - id: 12
     name: "Orel"
     type: "Cargo and Passenger"
   - id: 13
     name: "Mogilev"
     type: "Passenger"
   - id: 14
     name: "Kiev"
     type: "Cargo and Passenger"
trains:
   - id: 1
     name: "SPB - Warsaw"
     type: "Cargo and Passenger"
     power: 1400
     carriages:
        - type: "Passenger"
          amountOfContent: 10
        - type: "Passenger"
          amountOfContent: 10
        - type: "Passenger"
          amountOfContent: 10
        - type: "Cargo"
          amountOfContent: 10
        - type: "Cargo"
          amountOfContent: 10
     route:
        - 3
        - 2
        - 7
        - 1
        - 5
        - 6
   - id: 2
     name: "Riga - Orel"
     type: "Cargo and Passenger"
     power: 1800
     carriages:
       - type: "Passenger"
         amountOfContent: 50
       - type: "Passenger"
         amountOfContent: 40
       - type: "Passenger"
         amountOfContent: 30
       - type: "Cargo"
         amountOfContent: 100
       - type: "Cargo"
         amountOfContent: 50
       - type: "Cargo"
         amountOfContent: 0
     route:
       - 10
       - 11
       - 6
       - 8
       - 9
       - 7
       - 13
       - 12